# ~/docker-lab/compose-test/docker-compose.yml

services:
  nginx:
    image: nginx
    ports:
      - "8088:80"
    volumes:
      - ./nginx/html:/usr/share/nginx/html

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data

  activemq:
    image: apache/activemq-classic
    ports:
      - "8161:8161"    # 管理后台
      - "61616:61616"  # 消息端口
    volumes:
      - ./activemq-data:/opt/activemq/data